### ISSUE TITLE
Running phpunit cannot open file vendor/autoload.php

### ISSUE THREAD

**Issue by ismaail** [OussamaDEV/jsonfile#2]
I tried `phpunit` command in the folder `project_folder/vendor/devgol/jsonfile`

and it returns the error:
`Cannot open file "/home/ismaail/Developer/workspace/../project_folder/vendor/devgol/jsonfile/vendor/autoload.php"`

**Comment by OussamaDEV** [comment]
run `composer update` to install the required dependencies
or 
run `composer dumpautoload` to generate to generate the autoload.php file

if the problem style exist, please check:
do you have the autoload.php file inside the vendor directory ?

**Comment by ismaail** [comment]
My solution to run the testes is 
in the file `phpunit.xml` change  **bootstrap** value to 
`bootstrap="../../../vendor/autoload.php"`

**Comment by ismaail** [comment]
A better solution

Change [bootstrap](https://github.com/OussamaDEV/jsonfile/blob/master/phpunit.xml#L4) value to
`bootstrap="tests/Bootstrap.php"`

Add a new file `tests/Bootstrap.php` with the content:
```php
<?php
include __DIR__ . '/../../../autoload.php';
```

**Comment by OussamaDEV** [comment]
why do you require autoload.php 3 dirs up, what if the folder is in '/' ?
i think you have something wrong with your phpunit.

take a look, i've recorded my terminal
http://asciinema.org/a/4rlraoctb11d5cck5y40ujd5n

**Comment by ismaail** [comment]
The problem seems to be fixed after I reinstalled phpunit globally with composer this time.
